### PR TITLE
Added Suitest to Misc section

### PR DESCRIPTION
**Pull request by andriichumak**
The only object base test automation that covers all SmartTVs.

* [Suitest website](https://suite.st)
* [Suitest docs](https://suite.st/docs)
* [Suitest JS API](https://github.com/SuitestAutomation/suitest-js-api) for test automation

### CODE REVIEW

**Comment by vitalets** [comment]
Hi @andriichumak !

Thanks for pr! There was structure change in README, pls rebase on current master.

**Comment by andriichumak** [comment]
Hi @vitalets 

Done, sorry about the delay

**Comment by vitalets** [comment]
hi @andriichumak !

Let's make a separate section "Testing" and put there Suitest.

**Comment by andriichumak** [comment]
Like this?

**Comment by vitalets** [comment]
> Like this?

Yes! Thank you!

**Pull request merged**
